### ISSUE TITLE
bug in "RTM.m", Not enough input arguments.

### ISSUE THREAD

**Issue by shaocuifa** [ejchicaq-unal/RTM-MatLab-Code#1]
Hi Emiro Chica,

I downloaded the "RTM-MatLab-Code" and run the "RTM.m" file in matlab, then I enountered an error "Not enough input arguments." when FwdModelingFunction is called. 

I checked out the "RTM.m" file. In line 209 it calls FwdModelingFunction as 

 **[data, FwdSnapshot] = FwdModelingFunction(V,rw,nz,dz,nx,dx,nt,dt,ixs,izs,M,am,N);**

while the definition of  FwdModelingFunction  in  "FwdModelingFunction.m" file  is 

**function [data, FwdSnapshot] = FwdModelingFunction(V,rw,nz,~,nx,dx,nt,dt,ixs,izs,M,am,N,surec)**

It seems that there is a missing "surec" variable when calling FwdModelingFunction in  "RTM.m" file In line 209. So the "Not enough input arguments." reported.

Look forward for your reply.

best

**Comment by ejchicaq-unal** [comment]
Hi Shaocuifa

I'm glad you are interested in my code, thanks a lot.

You are rigth, there is a missing file called surec.mat which is a matrix with the source and receiver configuration.

I will make a correction and upload the code as a new version.

Again thanks for you comment.

**Comment by shaocuifa** [comment]
Thanks for your reply!

**Comment by shaocuifa** [comment]
> Hi Shaocuifa
> 
> I'm glad you are interested in my code, thanks a lot.
> 
> You are rigth, there is a missing file called surec.mat which is a matrix with the source and receiver configuration.
> 
> I will make a correction and upload the code as a new version.
> 
> Again thanks for you comment.

Thanks for your reply!

**Comment by ejchicaq-unal** [comment]
Hi Shaocuifa

Sorry for the delay; the surec.mat file have the source position, but it can be ignored; in fact I deleted that input in the code.

In the file RTM.m in lines 190, 191 and 192 you can set up the first shot position, the last shot position and the interval between sources.

I hope this can help you.

Best regards,

Emiro

**Comment by shaocuifa** [comment]
> Hi Shaocuifa
> 
> Sorry for the delay; the surec.mat file have the source position, but it can be ignored; in fact I deleted that input in the code.
> 
> In the file RTM.m in lines 190, 191 and 192 you can set up the first shot position, the last shot position and the interval between sources.
> 
> I hope this can help you.
> 
> Best regards,
> 
> Emiro

Thank you very much, I' ll check it later. Nice of you!
